cluster_max_size: 200000
cluster_min_size: 100
cluster_tol: 0.02
plane_dist_thresh: 0.001
plane_max_iter: 50
ror_min_neighbors: 5
ror_radius_search: 0.01
voxel_leaf_size: 0.0004
x_filter_max: 0.30
x_filter_min: -0.30
y_filter_max: 0.30
y_filter_min: -0.30
z_filter_max: 0.65
z_filter_min: 0.15
